# Generated by Django 5.2 on 2025-07-30 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='plat',
            name='est_epuise',
            field=models.BooleanField(default=False),
        ),
    ]
