# Generated by Django 5.1.2 on 2025-07-25 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='inconnu', max_length=100)),
                ('email', models.EmailField(default='inconnu@example.com', max_length=254)),
                ('telephone', models.CharField(default='0000000000', max_length=20)),
                ('date', models.DateField()),
                ('heure', models.TimeField(default='12:00')),
                ('type_table', models.CharField(choices=[('VIP', 'VIP'), ('Classique', 'Classique')], max_length=20)),
                ('nombre_personnes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('message', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
