# Generated by Django 5.1.2 on 2025-07-26 12:44

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Facture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('montant_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('date_emission', models.DateTimeField(default=django.utils.timezone.now)),
                ('payee', models.BooleanField(default=False)),
                ('commande', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='commande.commande')),
            ],
        ),
    ]
