# Generated by Django 5.1.2 on 2025-07-26 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='est_validee',
            field=models.BooleanField(default=False),
        ),
    ]
