# Generated by Django 5.1.2 on 2025-07-26 15:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0002_commande_est_validee'),
    ]

    operations = [
    ]
