# Generated by Django 5.1.2 on 2025-07-26 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0003_auto_20250726_1529'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='instruction',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='commande',
            name='status',
            field=models.CharField(choices=[('En cours', 'En cours'), ('Prête', 'Prête'), ('Servie', 'Servie'), ('Annulée', 'Annulée'), ('Livrée', 'Livrée')], default='En cours', max_length=50),
        ),
        migrations.AddField(
            model_name='commande',
            name='type_commande',
            field=models.CharField(choices=[('Sur place', 'Sur place'), ('À emporter', 'À emporter'), ('Livraison', 'Livraison')], default='Sur place', max_length=50),
        ),
    ]
