# Generated by Django 5.1.2 on 2025-07-26 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('commande', '0004_commande_instruction_commande_status_and_more'),
        ('menue', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commande',
            name='plat',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='menue.plat'),
        ),
    ]
