# Generated by Django 5.2 on 2025-07-28 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='date_envoi',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
