# Generated by Django 5.2 on 2025-07-29 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_message_date_envoi'),
    ]

    operations = [
        migrations.AddField(
            model_name='livreur',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='livreur',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
